fix: asprint.c build error (#25)
Currently the build fails with the following

```
util/asprintf.c: In function 'libutil_asprintf':
util/asprintf.c:38:7: warning: implicit declaration of function 'vasprintf' [-Wimplicit-function-declaration]
   r = vasprintf(ret, format, args);
       ^~~~~~~~~
```

Instead, call libutil_vasprintf directly instead of calling it through the vasprintf from the header.